### ISSUE TITLE
Application Panic/Crash

### ISSUE THREAD

**Issue by aantono** [elsevier-core-engineering/replicator#252]
Container crashes with the following error:

```
[INFO] command/agent: running version 1.0.3
[INFO] command/agent: starting replicator agent...
[INFO] command/agent: replicator is running with cluster scaling globally disabled
[INFO] command/agent: replicator is running with job scaling globally enabled
[INFO] client/job_scaling_policies: added new policy for job whoami and group whoami
[INFO] client/consul: leadership lock successfully obtained at replicator/config/leader
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0xa84d7b]

goroutine 15 [running]:
github.com/elsevier-core-engineering/replicator/client.(*nomadClient).IsJobInDeployment(0xc42000c558, 0xc4201d04f6, 0x6, 0x4558b0)
	/home/travis/gopath/src/github.com/elsevier-core-engineering/replicator/client/job_scaling.go:183 +0xdb
github.com/elsevier-core-engineering/replicator/replicator.(*Runner).asyncJobScaling(0xc4200bb860, 0xc42016ebd0)
	/home/travis/gopath/src/github.com/elsevier-core-engineering/replicator/replicator/job_scaling.go:28 +0xd6
github.com/elsevier-core-engineering/replicator/replicator.(*Runner).jobScalingTicker(0xc4200bb860, 0xc42016ebd0)
	/home/travis/gopath/src/github.com/elsevier-core-engineering/replicator/replicator/runner.go:99 +0x16f
created by github.com/elsevier-core-engineering/replicator/replicator.(*Runner).Start
	/home/travis/gopath/src/github.com/elsevier-core-engineering/replicator/replicator/runner.go:60 +0x220
[INFO] command/agent: running version 1.0.3
[INFO] command/agent: starting replicator agent...
[INFO] command/agent: replicator is running with cluster scaling globally disabled
[INFO] command/agent: replicator is running with job scaling globally enabled
[INFO] client/job_scaling_policies: added new policy for job whoami and group whoami
[INFO] client/consul: leadership lock successfully obtained at replicator/config/leader
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0xa84d7b]
```

The `replicator.nomad` file looks like this:
```
job "replicator" {
  datacenters = ["us-west-2-lab"]
  #region      = "global"
  type        = "service"

  update {
    stagger      = "10s"
    max_parallel = 1
  }

  meta {
    VERSION = "v1.0.3"
  }

  constraint {
    distinct_hosts = true
  }

  group "replicator" {
    count = 2

    task "replicator" {
      driver = "docker"

      config {
        image        = "elsce/replicator:${NOMAD_META_VERSION}"
        network_mode = "host"
        args         = [
          "agent",
          "-cluster-scaling-disable",
          "-statsd-address=127.0.0.1:8125",
        ]
      }

      resources {
        cpu    = 250
        memory = 60

        network {
          mbits = 5
        }
      }
    }
  }
}
```

The `whoami.nomad` job looks like this:
```
job "whoami" {
  #region      = "us-west-2"
  datacenters = ["us-west-2-lab"]
  type        = "service"

  group "whoami" {
    count = 2

    constraint {
      distinct_hosts = true
    } 

    meta {
      "replicator_cooldown"         = 30
      "replicator_enabled"          = true
      "replicator_max"              = 10
      "replicator_min"              = 1
      "replicator_scalein_mem"      = 30
      "replicator_scalein_cpu"      = 30
      "replicator_scaleout_mem"     = 80
      "replicator_scaleout_cpu"     = 80
      "replicator_notification_uid" = "REP1"
    }

    task "whoami" {
      driver = "docker"

      config {
        image = "emilevauge/whoami"

        port_map = {
          http = 80
        }
      }

      resources {
        cpu    = 100 # Mhz
        memory = 50  # MB

        network {
          mbits = 1

          port "http" {}
        }
      }
    }
  }
}
```

**Comment by ericwestfall** [comment]
Thanks for the bug report @aantono. 

What version of Nomad and Consul were you running when this bug occurred? I'm having trouble replicating the issue on my side.

**Comment by aantono** [comment]
I am using Nomad 0.7.1 and Consul 1.0.1.  The issue seems to only happen when the `job.nomad` is missing the `update` block.  As soon as I've added something like
```
update {
    stagger      = "10s"
    max_parallel = 1
  }
```
then the `Deployment` section in Nomad started showing up things, and the error went away.  If the job is deployed without `update` section, the `Deployment` in Nomad is not returning anything.  So based on the code `resp, _, err := c.nomad.Jobs().LatestDeployment(jobName, c.queryOptions())` my guess would be that since there is no deployments, the `LatestDeployment` is not existent, so it is returning `nil`

Does that make sense?

**Comment by aantono** [comment]
Did a bit more troubleshooting, and basically if `update` stanza is missing, for some reason Nomad API `/v1/job/<jobID>/deployment`, which is the call behind `.LatestDeployment(...)` method simply returns `null` as a response, not even a valid JSON object of empty, like `{}`, but just plain `null` string...  So that causes `resp` object be `nil` as well and no `err` at the same time.  So I think just adding a simple `resp == nil` check to `if err != nil {` to make it be: `if err != nil || resp == nil {` should do the trick. ;)

**Comment by aantono** [comment]
Filed an issue with Nomad as well - https://github.com/hashicorp/nomad/issues/3768

**Comment by jrasell** [comment]
@aantono I believe this is because Replicator relies on Nomad Deployments to truly tell the success of a job scale event, otherwise the register API call is a little fire and forget and the logic to check whether the job has scaled or not is quite complex. I believe we can take three approaches here:

1. Add functionality to check the health of a job that doesn't have an update stanza so we can verify scaling events
2. Add a simple clause which that if the job doesn't have an update stanza, a successful call to the Nomad API for a job register means a successful scale
3. Enforce an update stanza on all jobs that wish to subscribe to scaling activities

I would be interested in your feedback and thoughts on this. My preference is that all jobs that a user wishes to scale should have an update stanza which then allows us to use the Nomad deployment logic.

**Comment by aantono** [comment]
@jrasell I think your preferred solution sounds reasonable.  Based on the feedback in hashicorp/nomad#3768 the Deployment object is only created when an `update` stanza exists.  So it is reasonable to just check for a valid return, and if a `resp` is `nil`, just log a message saying that `update` stanza must be present, otherwise "no dice" :)  As long as it does not throw a panic fault, it should be good enough to expect it to be there, and ignore if it's not.

Thoughts?

**Comment by jrasell** [comment]
@aantono thanks for the feedback; I agree with you and am planning something like this and should have a PR ready later today and will get a release sorted sometime this week too:

```
	// The only reliable way to perform scaling is to use Nomad deployments; if
	// the job doesn't have an update stanza then it won't use deployments so we
	// do not allow it to be added for scaling.
	if jobInfo.Update == new(nomad.UpdateStrategy) {
		logging.Debug("client/job_scaling_policies: job %s can't be scaled, update stanza is empty", jobID)
		return
	}
```
