### ISSUE TITLE
Crash When Allocation Node Count or Capacity Data Is Zero

### ISSUE THREAD

**Issue by ericwestfall** [elsevier-core-engineering/replicator#5]
The `PercentageCapacityRequired` function causes a runtime panic if we are unable to retrieve allocation information: 

```
LNGDAYM-4172503:replicator westfaex$ replicator
Cluster Allocation: 0, 0, 0panic: runtime error: integer divide by zero

goroutine 7 [running]:
github.com/elsevier-core-engineering/replicator/replicator.(*Runner).Start(0xc420146d90)
	/Users/westfaex/code/go/src/github.com/elsevier-core-engineering/replicator/replicator/runner.go:47 +0x629
created by github.com/elsevier-core-engineering/replicator/replicator.(*CLI).Run
	/Users/westfaex/code/go/src/github.com/elsevier-core-engineering/replicator/replicator/cli.go:46 +0x112
LNGDAYM-4172503:replicator westfaex$ go install && replicator
```

We just need to make sure we either add zero-value protection to the `PercentageCapacityRequired` method or make sure we don't call the method when we don't have the information necessary to calculate the required capacity.

**Comment by jrasell** [comment]
Unable to reproduce with latest code changes.

**Comment by ericwestfall** [comment]
Reproduced this issue again this evening when working against a single dev mode Nomad cluster that resumed when my box came up from sleep mode. It seems possible that if Nomad is in a flaky or unstable state and the healthy node count is 0, even temporarily, we can hit this panic. 

We can easily address this by not evaluating maximum allowed capacity utilization when we the healthy node count is 0. 

```
 ✘  ~/code/go/src/github.com/elsevier-core-engineering/replicator   job-scaling-dryrun ●  ./replicator-local agent -config=/Users/westfaex/Downloads/replicator.config
[DEBUG] command/agent: running version 0.0.1-dev
[DEBUG] Node Count: 0
panic: runtime error: integer divide by zero

goroutine 51 [running]:
github.com/elsevier-core-engineering/replicator/api.MaxAllowedClusterUtilization(0xc42060a000, 0x1, 0x0, 0x0)
	/Users/westfaex/code/go/src/github.com/elsevier-core-engineering/replicator/api/nomad.go:635 +0x566
github.com/elsevier-core-engineering/replicator/api.(*nomadClient).EvaluateClusterCapacity(0xc420184090, 0xc42060a000, 0xc4201aad80, 0x0, 0x0, 0x0)
	/Users/westfaex/code/go/src/github.com/elsevier-core-engineering/replicator/api/nomad.go:76 +0x118
github.com/elsevier-core-engineering/replicator/replicator.(*Runner).clusterScaling(0xc420566120, 0xc42056c060)
	/Users/westfaex/code/go/src/github.com/elsevier-core-engineering/replicator/replicator/runner.go:82 +0xd1
created by github.com/elsevier-core-engineering/replicator/replicator.(*Runner).Start
	/Users/westfaex/code/go/src/github.com/elsevier-core-engineering/replicator/replicator/runner.go:42 +0x143
```

**Comment by ericwestfall** [comment]
Reproduced this issue again this evening when working against a single dev mode Nomad cluster that resumed when my box came up from sleep mode. It seems possible that if Nomad is in a flaky or unstable state and the healthy node count is 0, even temporarily, we can hit this panic. 

We can easily address this by not evaluating maximum allowed capacity utilization when we the healthy node count is 0. 

```
 ✘  ~/code/go/src/github.com/elsevier-core-engineering/replicator   job-scaling-dryrun ●  ./replicator-local agent -config=/Users/westfaex/Downloads/replicator.config
[DEBUG] command/agent: running version 0.0.1-dev
[DEBUG] Node Count: 0
panic: runtime error: integer divide by zero

goroutine 51 [running]:
github.com/elsevier-core-engineering/replicator/api.MaxAllowedClusterUtilization(0xc42060a000, 0x1, 0x0, 0x0)
	/Users/westfaex/code/go/src/github.com/elsevier-core-engineering/replicator/api/nomad.go:635 +0x566
github.com/elsevier-core-engineering/replicator/api.(*nomadClient).EvaluateClusterCapacity(0xc420184090, 0xc42060a000, 0xc4201aad80, 0x0, 0x0, 0x0)
	/Users/westfaex/code/go/src/github.com/elsevier-core-engineering/replicator/api/nomad.go:76 +0x118
github.com/elsevier-core-engineering/replicator/replicator.(*Runner).clusterScaling(0xc420566120, 0xc42056c060)
	/Users/westfaex/code/go/src/github.com/elsevier-core-engineering/replicator/replicator/runner.go:82 +0xd1
created by github.com/elsevier-core-engineering/replicator/replicator.(*Runner).Start
	/Users/westfaex/code/go/src/github.com/elsevier-core-engineering/replicator/replicator/runner.go:42 +0x143
```

**Comment by ericwestfall** [comment]
Seems the simplest approach is to detect a situation where we've detected no healthy nodes in the cluster and short-circuit the scaling evaluation. Something like this in the `EvaluateClusterCapacity` method of `api/nomad`: 

```
	if capacity.NodeCount <= 0 {
		logging.Debug("api/nomad: no healthy nodes detected, halting cluster scaling evaluation")
		return 
	}
```
